//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNongSanEntities : DbContext
    {
        public QLNongSanEntities()
            : base("name=QLNongSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminBC> AdminBCs { get; set; }
        public virtual DbSet<ColumnSelected> ColumnSelecteds { get; set; }
        public virtual DbSet<NewNoti> NewNotis { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductPlantingProcess> ProductPlantingProcesses { get; set; }
        public virtual DbSet<ProductTranfer> ProductTranfers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserBC> UserBCs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ProductDetailView> ProductDetailViews { get; set; }
        public virtual DbSet<ProductSentView> ProductSentViews { get; set; }
        public virtual DbSet<QRManager> QRManagers { get; set; }
    }
}
