//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNongSanEntities : DbContext
    {
        public QLNongSanEntities()
            : base("name=QLNongSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amsm> amsms { get; set; }
        public virtual DbSet<custommer> custommers { get; set; }
        public virtual DbSet<memberUser> memberUsers { get; set; }
        public virtual DbSet<theFarm> theFarms { get; set; }
    }
}
