//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewNoti
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public string idProduct { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public string detail { get; set; }
    }
}
