//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSentView
    {
        public Nullable<long> id { get; set; }
        public string idProduct { get; set; }
        public string nameProduct { get; set; }
        public string idUser { get; set; }
        public string nameOfUser { get; set; }
        public string details { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> sentNumber { get; set; }
    }
}
