//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetailView
    {
        public Nullable<long> id { get; set; }
        public int idProductDetail { get; set; }
        public string idUser { get; set; }
        public string nameOfUser { get; set; }
        public string idProduct { get; set; }
        public string nameProduct { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateReview { get; set; }
        public string email { get; set; }
        public string adrs { get; set; }
        public string phone { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> IsUpBD { get; set; }
        public string userArea { get; set; }
        public string userCity { get; set; }
    }
}
