//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
	using System;
	using System.Collections.Generic;

	public partial class ProductTranfer
	{
		public int id { get; set; }
		public string idProduct { get; set; }
		public string nameProduct { get; set; }
		public string nameUser { get; set; }
		public string detail { get; set; }
		public string idUser { get; set; }
		public Nullable<int> numberTranfer { get; set; }
		public Nullable<int> isClick { get; set; }
		public Nullable<int> idProductDetail { get; set; }
		public string company { get; set; }
	}
}