//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
	using System;
	using System.Collections.Generic;

	public partial class QRManager
	{
		public int id { get; set; }
		public string idProduct { get; set; }
		public string linkImg { get; set; }
		public string idUserRequest { get; set; }
		public Nullable<int> amount { get; set; }
		public Nullable<int> accepted { get; set; }
		public Nullable<System.DateTime> dateCreated { get; set; }
		public Nullable<System.DateTime> dateUpdated { get; set; }
		public Nullable<int> isDeleted { get; set; }
	}
}