//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigchainDBWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class theFarm
    {
        public int id { get; set; }
        public Nullable<int> idCustommer { get; set; }
        public string adrs { get; set; }
    
        public virtual custommer custommer { get; set; }
    }
}
